---
apiVersion: v1
kind: Service
metadata:
  name: books
  namespace: beta-apps
  labels:
    env: development
spec:
  selector:
    app: books
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---