---
apiVersion: v1
kind: Service
metadata:
  name: books
  namespace: beta-apps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    env: development
spec:
  selector:
    app: books
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
